# syntax=docker/dockerfile:experimental

ARG PYTHON_VERSION

FROM ${PYTHON_VERSION}
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y build-essential ocrfeeder
RUN --mount=type=cache,target=/root/.cache/pip pip install -U pip tox-factor flake8 isort check-manifest
