version: "3.8"

volumes:
  pip_cache:

services:

  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=password

  py37: &pyenv
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        PYTHON_VERSION: python:3.7

    volumes:
      - .:/factory_boy
    depends_on:
      - mongo
      - postgres
    environment:
      - PYENV_NAME=py37
    command: bash -c 'POSTGRES_DATABASE=factory_boy_test_$$PYENV_NAME tox -f $$PYENV_NAME'

  py38:
    <<: *pyenv
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        PYTHON_VERSION: python:3.8
    environment:
      - PYENV_NAME=py38

  py39:
    <<: *pyenv
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        PYTHON_VERSION: python:3.9
    environment:
      - PYENV_NAME=py39

  py310:
    <<: *pyenv
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        PYTHON_VERSION: python:3.10
    environment:
      - PYENV_NAME=py310

  pypy37:
    <<: *pyenv
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        PYTHON_VERSION: pypy:3.7
    environment:
      - PYENV_NAME=pypy37

  pypy38:
    <<: *pyenv
    build:
      context: .
      dockerfile: Dockerfile.template
      args:
        PYTHON_VERSION: pypy:3.8
    environment:
      - PYENV_NAME=pypy38
