name: Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          # - "3.8"
          # - "3.9"
          - "3.10"
          # - "pypy-3.8"
        tox-environment:
          - django32-alchemy-mongoengine-postgres
          - django40-alchemy-mongoengine-postgres
        include:
          - python-version: "3.7"
            tox-environment: django22-alchemy-mongoengine
          - python-version: "pypy-3.7"
            tox-environment: django22-alchemy-mongoengine
          - python-version: "3.7"
            tox-environment: django32-alchemy-mongoengine
          - python-version: "pypy-3.7"
            tox-environment: django32-alchemy-mongoengine
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

      postgresdb:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD:
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TOXENV: ${{ matrix.tox-environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox
