name: Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Python ${{ matrix.python-version }} / ${{ matrix.tox-environment }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "pypy-3.8"
        tox-environment:
          - django32-sqlite
          - django32-postgres
          - django40-sqlite
          - django40-postgres
        include:
          - python-version: "3.7"
            tox-environment: django22-sqlite
          - python-version: "3.7"
            tox-environment: django22-postgres
          - python-version: "pypy-3.7"
            tox-environment: django22-sqlite
          - python-version: "pypy-3.7"
            tox-environment: django22-postgres
          - python-version: "3.7"
            tox-environment: django32-sqlite
          - python-version: "3.7"
            tox-environment: django32-postgres
          - python-version: "pypy-3.7"
            tox-environment: django32-sqlite
          - python-version: "pypy-3.7"
            tox-environment: django32-postgres
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

      postgresdb:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password

    env:
      TOXENV: ${{ matrix.tox-environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install tox tox-gh-actions

      - name: Run tests
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
